export type LegalPage = "privacy" | "terms";

interface LegalSection {
  id: string;
  heading: string;
  paragraphs: string[];
}

interface LegalDocument {
  intro: string;
  updated: string;
  sections: LegalSection[];
}

type LegalDocuments = Record<LegalPage, LegalDocument>;

const updated = {
  en: "Last updated: 26 August 2026",
  tr: "Son güncelleme: 26 Ağustos 2026",
  de: "Zuletzt aktualisiert: 26. August 2026",
  es: "Última actualización: 26 de agosto de 2026",
  fr: "Dernière mise à jour : 26 août 2026",
  it: "Ultimo aggiornamento: 26 agosto 2026",
  "pt-br": "Última atualização: 26 de agosto de 2026",
} as const;

const contentsLabels = {
  en: "On this page",
  tr: "Bu sayfada",
  de: "Auf dieser Seite",
  es: "En esta página",
  fr: "Sur cette page",
  it: "In questa pagina",
  "pt-br": "Nesta página",
} as const;

const documents: Record<keyof typeof updated, LegalDocuments> = {
  en: {
    privacy: {
      intro: "This notice explains how Notura handles personal information when you use the app and its related services.",
      updated: updated.en,
      sections: [
        { id: "information", heading: "Information we collect", paragraphs: ["We collect the information needed to provide your account and nutrition-tracking experience. This can include your email address and basic account details; profile information you choose to provide; food entries, meal photos, food descriptions, calorie and macronutrient information; water and weight records; and goals and preferences. If you use Community, we also process the content, comments and reactions you choose to share there."] },
        { id: "how-we-use", heading: "How we use information", paragraphs: ["We use this information to run and improve the features you choose, keep your records available across your account, personalise your settings and goals, provide support, protect the service, and meet legal obligations. We do not use your personal diary as public Community content unless you choose to share it."] },
        { id: "providers-location", heading: "Service providers and data location", paragraphs: ["Notura uses Supabase as a hosting, backend and service provider. Our primary server and data region is Ireland in the European Union. Providers may process information as needed to provide their services and under suitable safeguards; this does not mean information can never be accessed or processed outside Ireland."] },
        { id: "sign-in", heading: "Google and Apple sign-in", paragraphs: ["Google sign-in is available through a third-party authentication service. Apple sign-in may be offered in a future version. When you choose one of these methods, we may receive the basic account information needed to authenticate and create your Notura account. Notura does not receive your Google or Apple password."] },
        { id: "ai", heading: "AI features", paragraphs: ["Notura may use AI to analyse a meal photo or written meal description, and to provide meal suggestions. We send only the content needed for that request, such as the photo, your description, or limited information needed for a suggestion. We do not add your name, email address, account identifier or broad profile history to an AI request when it is not needed. A photo or text you submit can itself contain personal information, so we do not make an absolute promise that no personal information is ever sent. AI results are intended to help you log and review meals."] },
        { id: "community", heading: "Community sharing and the 30-day rule", paragraphs: ["Community sharing is off by default. You choose whether to enable it and, in the relevant product flow, whether to share eligible past records. Community keeps and displays relevant shares from the most recent 30 days only. When a Community post reaches 30 days, it is removed from Community together with its comments and reactions. This does not delete the personal meal or diary record in your account. You can hide an individual record from Community, and available privacy controls such as blocking are applied within the feature."] },
        { id: "retention-rights", heading: "Retention, your account and your choices", paragraphs: ["We keep account and personal app data while it is needed to provide the service. When you delete your account, associated data is deleted subject to technical, security and legal requirements; limited records may need to be retained longer where required for those purposes. Community content follows the separate 30-day rule above. You can request access to, correction of, deletion of, or—where available—export of your information, and withdraw consent where processing relies on it. Make privacy requests through the support option available in the app."] },
        { id: "regional-rights", heading: "Regional privacy rights", paragraphs: ["Depending on where you live, you may have additional rights. In Türkiye, rights under KVKK are reserved. In the EEA and EU, GDPR rights can include access, correction, deletion, restriction, objection and portability. Similar rights may apply in the United Kingdom under UK GDPR and the Data Protection Act, in Brazil under LGPD, and under applicable United States federal or state privacy laws. You may also have the right to complain to the relevant data-protection authority."] },
        { id: "security-children", heading: "Security and children", paragraphs: ["We use reasonable technical and organisational measures designed to protect information. No internet service can be completely secure. Notura has not set a public age threshold on this website. If we learn that information from a child was collected contrary to applicable law, we will take appropriate steps to address it."] },
        { id: "changes-contact", heading: "Changes and contact", paragraphs: ["We may update this notice as Notura or applicable law changes. The current version and its update date will be posted here. A dedicated public privacy email address is not currently published on this website; for a privacy request, use the support route available in the app."] },
      ],
    },
    terms: {
      intro: "These terms set out the simple rules for using Notura.",
      updated: updated.en,
      sections: [
        { id: "service", heading: "What Notura is", paragraphs: ["Notura is a nutrition and wellness tracking service. It can help you record food, understand calorie and macronutrient context, and track related goals. It is not a medical device, diagnostic service, or a replacement for a doctor, dietitian or other qualified health professional."] },
        { id: "health-ai", heading: "Health and AI information", paragraphs: ["AI can make mistakes when identifying food, estimating portions or nutrition values, and making suggestions. Review results before relying on them and do not use them as the sole basis for critical health decisions. For allergies, medical conditions, medicines, pregnancy or a clinical diet, seek advice from a qualified health professional."] },
        { id: "account", heading: "Your account", paragraphs: ["You are responsible for activity through your account and for keeping your sign-in method secure. Use Notura lawfully and do not misuse, interfere with, or attempt to access accounts or data that are not yours. You may delete your account. We may limit or suspend access where there is misuse, a security risk, or a legal reason."] },
        { id: "community", heading: "Community rules", paragraphs: ["If Community is available to you, keep it respectful and lawful. Do not post harassment, spam, unlawful material, content that infringes another person’s rights, or anything that misuses the service. We may remove Community content or limit access when reasonably needed to enforce these rules or protect people and the service. Community posts, comments and reactions are removed after 30 days; your private diary record is not removed by that Community retention process."] },
        { id: "your-content", heading: "Your content", paragraphs: ["You keep ownership of the content you submit. You give Notura the limited permission needed to host, process, display to you, and—only if you choose Community sharing—display it within Community, so that we can provide the service. That permission ends when the relevant content is deleted, subject to necessary technical, security and legal retention."] },
        { id: "plans", heading: "Free and paid features", paragraphs: ["Some features may be free and some may require a paid plan or purchase in the future. If payment applies, the price and payment terms will be shown before purchase. Purchases, restores and refunds made through Google Play or the Apple App Store may also be governed by that store’s rules."] },
        { id: "availability-liability", heading: "Availability and responsibility", paragraphs: ["Notura is provided on an “as available” basis. We work to keep it useful and reliable, but do not guarantee that AI results will always be accurate or that the service will always be uninterrupted, including where third-party services are unavailable. Nothing in these terms excludes responsibility that cannot lawfully be excluded."] },
        { id: "changes-contact", heading: "Changes and contact", paragraphs: ["We may update these terms and will post the current version and update date on this page. If you do not agree with a material change, stop using Notura and delete your account. A dedicated public legal contact email is not currently published on this website; use the support route available in the app for questions."] },
      ],
    },
  },
  tr: {
    privacy: {
      intro: "Bu bildirim, Notura uygulamasını ve ilgili hizmetlerini kullanırken kişisel bilgilerinizi nasıl işlediğimizi açıklar.",
      updated: updated.tr,
      sections: [
        { id: "information", heading: "Topladığımız bilgiler", paragraphs: ["Hesabınızı ve beslenme takibi deneyiminizi sunmak için gerekli bilgileri toplarız. Bunlar e-posta adresiniz ve temel hesap bilgileriniz; paylaşmayı seçtiğiniz profil bilgileri; yemek kayıtları, yemek fotoğrafları, yemek açıklamaları, kalori ve makro besin bilgileri; su ve kilo kayıtları; hedefler ve tercihler olabilir. Community'yi kullanırsanız, paylaşmayı seçtiğiniz içerik, yorum ve reaksiyonları da işleriz."] },
        { id: "how-we-use", heading: "Bilgileri nasıl kullanırız", paragraphs: ["Bilgileri, seçtiğiniz özellikleri çalıştırmak ve geliştirmek, kayıtlarınızı hesabınızda kullanılabilir tutmak, ayarlarınızı ve hedeflerinizi kişiselleştirmek, destek vermek, hizmeti korumak ve yasal yükümlülükleri yerine getirmek için kullanırız. Siz paylaşmayı seçmedikçe kişisel günlüğünüzü herkese açık Community içeriği olarak kullanmayız."] },
        { id: "providers-location", heading: "Hizmet sağlayıcılar ve veri konumu", paragraphs: ["Notura, barındırma, backend ve hizmet sağlayıcısı olarak Supabase kullanır. Birincil sunucu ve veri bölgemiz Avrupa Birliği'ndeki İrlanda'dır. Sağlayıcılar, hizmetlerini sunmak için gerekli olduğunda ve uygun güvenceler altında bilgi işleyebilir; bu, bilgilerin İrlanda dışında hiçbir zaman erişilemeyeceği veya işlenmeyeceği anlamına gelmez."] },
        { id: "sign-in", heading: "Google ve Apple ile giriş", paragraphs: ["Google ile giriş, üçüncü taraf bir kimlik doğrulama hizmeti üzerinden kullanılabilir. Apple ile giriş gelecekte sunulabilir. Bu yöntemlerden birini seçtiğinizde, kimlik doğrulamak ve Notura hesabınızı oluşturmak için gereken temel hesap bilgilerini alabiliriz. Notura, Google veya Apple parolanızı almaz."] },
        { id: "ai", heading: "Yapay zekâ özellikleri", paragraphs: ["Notura, yemek fotoğrafını veya yazılı yemek açıklamasını analiz etmek ve yemek önerileri sunmak için yapay zekâ kullanabilir. İsteğe yalnızca gereken içeriği; örneğin fotoğrafı, açıklamanızı veya öneri için gerekli sınırlı bilgiyi göndeririz. Gerekmedikçe adınızı, e-posta adresinizi, hesap kimliğinizi veya geniş profil geçmişinizi yapay zekâ isteğine eklemeyiz. Gönderdiğiniz fotoğraf ya da metin kişisel bilgi içerebileceğinden, hiçbir kişisel bilginin asla gönderilmediğine dair mutlak bir söz vermeyiz. Yapay zekâ sonuçları, yemeklerinizi kaydetmenize ve gözden geçirmenize yardımcı olmak içindir."] },
        { id: "community", heading: "Community paylaşımı ve 30 gün kuralı", paragraphs: ["Community paylaşımı varsayılan olarak kapalıdır. Etkinleştirmeyi ve ilgili ürün akışında uygun geçmiş kayıtları paylaşmayı siz seçersiniz. Community yalnızca son 30 gün içindeki ilgili paylaşımları saklar ve gösterir. Bir Community gönderisi 30 günü doldurduğunda, yorumları ve reaksiyonlarıyla birlikte Community'den kaldırılır. Bu işlem hesabınızdaki kişisel yemek veya günlük kaydını silmez. Belirli bir kaydı Community'den gizleyebilir; engelleme gibi mevcut gizlilik kontrollerini özellik içinde kullanabilirsiniz."] },
        { id: "retention-rights", heading: "Saklama, hesabınız ve seçimleriniz", paragraphs: ["Hesap ve kişisel uygulama verilerini hizmeti sunmak için gerekli olduğu sürece tutarız. Hesabınızı sildiğinizde, ilişkili veriler teknik, güvenlik ve yasal gerekliliklere tabi olarak silinir; bu amaçlarla sınırlı kayıtların daha uzun tutulması gerekebilir. Community içeriği yukarıdaki ayrı 30 gün kuralına tabidir. Bilgilerinize erişim, düzeltme, silme ve mevcutsa dışa aktarma talebinde bulunabilir; işleme rızaya dayanıyorsa rızanızı geri çekebilirsiniz. Gizlilik taleplerinizi uygulamadaki destek seçeneği üzerinden iletin."] },
        { id: "regional-rights", heading: "Bölgesel gizlilik hakları", paragraphs: ["Yaşadığınız yere göre ek haklarınız olabilir. Türkiye'de KVKK kapsamındaki haklar saklıdır. EEA ve AB'de GDPR kapsamındaki haklar erişim, düzeltme, silme, kısıtlama, itiraz ve taşınabilirliği içerebilir. Birleşik Krallık'ta UK GDPR ve Data Protection Act, Brezilya'da LGPD, Amerika Birleşik Devletleri'nde ise uygulanabilir federal veya eyalet gizlilik yasaları uyarınca benzer haklar geçerli olabilir. İlgili veri koruma makamına şikâyette bulunma hakkınız da olabilir."] },
        { id: "security-children", heading: "Güvenlik ve çocuklar", paragraphs: ["Bilgileri korumak için makul teknik ve organizasyonel önlemler kullanırız. Hiçbir internet hizmeti tamamen güvenli değildir. Notura bu web sitesinde herkese açık bir yaş eşiği belirlememiştir. Bir çocuğa ait bilginin yürürlükteki hukuka aykırı olarak toplandığını öğrenirsek, durumu ele almak için uygun adımları atarız."] },
        { id: "changes-contact", heading: "Değişiklikler ve iletişim", paragraphs: ["Notura veya yürürlükteki hukuk değiştikçe bu bildirimi güncelleyebiliriz. Güncel sürümü ve güncelleme tarihini burada yayımlarız. Bu web sitesinde özel, herkese açık bir gizlilik e-posta adresi henüz yayımlanmamıştır; gizlilik talebi için uygulamadaki destek yolunu kullanın."] },
      ],
    },
    terms: {
      intro: "Bu koşullar, Notura'yı kullanmanın temel kurallarını açıklar.",
      updated: updated.tr,
      sections: [
        { id: "service", heading: "Notura nedir?", paragraphs: ["Notura, beslenme ve iyi yaşam takibi hizmetidir. Yiyecek kaydetmenize, kalori ve makro besin bağlamını anlamanıza ve ilgili hedefleri takip etmenize yardımcı olabilir. Tıbbi cihaz, tanı hizmeti veya doktor, diyetisyen ya da diğer nitelikli sağlık profesyonellerinin yerine geçen bir hizmet değildir."] },
        { id: "health-ai", heading: "Sağlık ve yapay zekâ bilgileri", paragraphs: ["Yapay zekâ; yiyecekleri tanırken, porsiyon veya besin değeri tahmin ederken ve öneri üretirken hata yapabilir. Sonuçları kullanmadan önce gözden geçirin; kritik sağlık kararlarında tek kaynak olarak kullanmayın. Alerji, hastalık, ilaç kullanımı, gebelik veya klinik diyet durumlarında nitelikli bir sağlık profesyoneline danışın."] },
        { id: "account", heading: "Hesabınız", paragraphs: ["Hesabınızdaki etkinlikten ve giriş yönteminizi güvenli tutmaktan siz sorumlusunuz. Notura'yı hukuka uygun kullanın; kötüye kullanmayın, çalışmasını engellemeyin veya size ait olmayan hesap ya da verilere erişmeye çalışmayın. Hesabınızı silebilirsiniz. Kötüye kullanım, güvenlik riski veya yasal neden olduğunda erişimi sınırlayabilir ya da askıya alabiliriz."] },
        { id: "community", heading: "Community kuralları", paragraphs: ["Community size sunulduğunda saygılı ve hukuka uygun davranın. Taciz, spam, yasa dışı içerik, başkasının haklarını ihlal eden içerik veya hizmeti kötüye kullanan içerik paylaşmayın. Bu kuralları uygulamak veya kişileri ve hizmeti korumak için gerektiğinde Community içeriğini kaldırabilir ya da erişimi sınırlayabiliriz. Community gönderileri, yorumları ve reaksiyonları 30 gün sonra kaldırılır; kişisel günlük kaydınız bu Community saklama işlemiyle kaldırılmaz."] },
        { id: "your-content", heading: "İçeriğiniz", paragraphs: ["Gönderdiğiniz içeriğin sahipliği sizde kalır. Hizmeti sunabilmemiz için, içeriğinizi barındırmak, işlemek, size göstermek ve yalnızca Community paylaşımını seçerseniz Community içinde göstermek üzere Notura'ya sınırlı izin verirsiniz. Gerekli teknik, güvenlik ve yasal saklama durumları hariç, ilgili içerik silindiğinde bu izin sona erer."] },
        { id: "plans", heading: "Ücretsiz ve ücretli özellikler", paragraphs: ["Bazı özellikler ücretsiz olabilir; bazıları ise gelecekte ücretli plan veya satın alma gerektirebilir. Ödeme gerektiğinde fiyat ve ödeme koşulları satın alma öncesinde gösterilir. Google Play veya Apple App Store üzerinden yapılan satın alma, geri yükleme ve iade işlemleri ilgili mağazanın kurallarına da tabi olabilir."] },
        { id: "availability-liability", heading: "Kullanılabilirlik ve sorumluluk", paragraphs: ["Notura 'mevcut olduğu şekliyle' sunulur. Yararlı ve güvenilir tutmak için çalışırız; ancak yapay zekâ sonuçlarının her zaman doğru olacağını veya üçüncü taraf hizmetlerin kullanılamadığı durumlar da dâhil olmak üzere hizmetin her zaman kesintisiz olacağını garanti etmeyiz. Bu koşullardaki hiçbir hüküm, hukuken dışlanamayacak sorumluluğu dışlamaz."] },
        { id: "changes-contact", heading: "Değişiklikler ve iletişim", paragraphs: ["Bu koşulları güncelleyebilir, güncel sürümü ve güncelleme tarihini bu sayfada yayımlayabiliriz. Esaslı bir değişikliği kabul etmiyorsanız Notura'yı kullanmayı bırakın ve hesabınızı silin. Bu web sitesinde özel, herkese açık bir hukuk iletişim e-posta adresi henüz yayımlanmamıştır; sorular için uygulamadaki destek yolunu kullanın."] },
      ],
    },
  },
  de: { privacy: { intro: "Diese Hinweise erläutern, wie Notura personenbezogene Daten bei der Nutzung der App und verbundener Dienste verarbeitet.", updated: updated.de, sections: [
    { id: "information", heading: "Welche Daten wir erfassen", paragraphs: ["Wir erfassen die Daten, die für Ihr Konto und die Ernährungsdokumentation erforderlich sind: E-Mail-Adresse und grundlegende Kontodaten, freiwillige Profilangaben, Mahlzeiteneinträge, Essensfotos und -beschreibungen, Kalorien- und Makronährwertangaben, Wasser- und Gewichtsaufzeichnungen sowie Ziele und Einstellungen. Bei Nutzung von Community verarbeiten wir auch die von Ihnen geteilten Beiträge, Kommentare und Reaktionen."] },
    { id: "how-we-use", heading: "Wie wir Daten verwenden", paragraphs: ["Wir verwenden die Daten, um die von Ihnen gewählten Funktionen bereitzustellen und zu verbessern, Aufzeichnungen für Ihr Konto verfügbar zu halten, Einstellungen und Ziele anzupassen, Support zu leisten, den Dienst zu schützen und gesetzlichen Pflichten nachzukommen. Ihr persönliches Tagebuch wird nicht als öffentlicher Community-Inhalt genutzt, es sei denn, Sie entscheiden sich dafür."] },
    { id: "providers-location", heading: "Dienstleister und Datenstandort", paragraphs: ["Notura nutzt Supabase als Hosting-, Backend- und Dienstleister. Unsere primäre Server- und Datenregion ist Irland in der Europäischen Union. Dienstleister können Daten unter geeigneten Schutzmaßnahmen verarbeiten, soweit dies für ihre Dienste nötig ist; daraus folgt nicht, dass Daten niemals außerhalb Irlands abgerufen oder verarbeitet werden."] },
    { id: "sign-in", heading: "Anmeldung mit Google und Apple", paragraphs: ["Die Anmeldung mit Google ist über einen Drittanbieter-Authentifizierungsdienst verfügbar. Eine Anmeldung mit Apple kann künftig angeboten werden. Bei Wahl einer dieser Methoden können wir die grundlegenden Kontodaten erhalten, die zur Anmeldung und Kontoerstellung nötig sind. Notura erhält weder Ihr Google- noch Ihr Apple-Passwort."] },
    { id: "ai", heading: "KI-Funktionen", paragraphs: ["Notura kann KI zur Analyse von Essensfotos oder -beschreibungen und für Mahlzeitenvorschläge einsetzen. Wir senden nur die für die Anfrage erforderlichen Inhalte, etwa Foto, Beschreibung oder begrenzte Daten für einen Vorschlag. Name, E-Mail-Adresse, Konto-ID oder umfangreiche Profilhistorie fügen wir nicht hinzu, wenn sie nicht erforderlich sind. Ein eingereichtes Foto oder Text kann selbst personenbezogene Daten enthalten; daher versprechen wir nicht absolut, dass nie personenbezogene Daten übermittelt werden. KI-Ergebnisse sollen beim Erfassen und Prüfen von Mahlzeiten helfen."] },
    { id: "community", heading: "Community und die 30-Tage-Regel", paragraphs: ["Community-Freigabe ist standardmäßig deaktiviert. Sie entscheiden, ob Sie sie aktivieren und im vorgesehenen Ablauf auch geeignete frühere Einträge teilen. Community speichert und zeigt nur relevante Freigaben der letzten 30 Tage. Nach 30 Tagen wird ein Beitrag samt Kommentaren und Reaktionen aus Community entfernt. Ihr persönlicher Mahlzeiten- oder Tagebucheintrag im Konto wird dadurch nicht gelöscht. Sie können einzelne Einträge aus Community ausblenden und vorhandene Datenschutzkontrollen wie Blockieren nutzen."] },
    { id: "retention-rights", heading: "Aufbewahrung, Konto und Ihre Wahlmöglichkeiten", paragraphs: ["Wir bewahren Konto- und persönliche App-Daten so lange auf, wie dies für den Dienst erforderlich ist. Nach Löschung Ihres Kontos werden zugehörige Daten vorbehaltlich technischer, Sicherheits- und Rechtsanforderungen gelöscht; begrenzte Aufzeichnungen können dafür länger erforderlich sein. Für Community gilt die separate 30-Tage-Regel. Sie können Zugang, Berichtigung, Löschung und – soweit verfügbar – Export Ihrer Daten verlangen und eine Einwilligung widerrufen, wenn die Verarbeitung darauf beruht. Nutzen Sie für Datenschutzanfragen die Support-Option in der App."] },
    { id: "regional-rights", heading: "Regionale Datenschutzrechte", paragraphs: ["Je nach Wohnort stehen Ihnen zusätzliche Rechte zu. In der Türkei bleiben Rechte nach KVKK vorbehalten. Im EWR und der EU können GDPR-Rechte Zugang, Berichtigung, Löschung, Einschränkung, Widerspruch und Datenübertragbarkeit umfassen. Entsprechende Rechte können im Vereinigten Königreich nach UK GDPR und Data Protection Act, in Brasilien nach LGPD und nach anwendbarem US-Bundes- oder einzelstaatlichem Datenschutzrecht gelten. Sie können sich auch bei der zuständigen Datenschutzbehörde beschweren."] },
    { id: "security-children", heading: "Sicherheit und Kinder", paragraphs: ["Wir setzen angemessene technische und organisatorische Maßnahmen zum Schutz von Daten ein. Kein Internetdienst ist vollständig sicher. Notura hat auf dieser Website keine öffentliche Altersgrenze festgelegt. Erfahren wir, dass Daten eines Kindes entgegen geltendem Recht erhoben wurden, treffen wir angemessene Maßnahmen."] },
    { id: "changes-contact", heading: "Änderungen und Kontakt", paragraphs: ["Wir können diese Hinweise aktualisieren, wenn sich Notura oder das anwendbare Recht ändert. Die aktuelle Fassung und das Aktualisierungsdatum stehen auf dieser Seite. Eine eigene öffentliche Datenschutz-E-Mail-Adresse ist auf dieser Website noch nicht veröffentlicht; nutzen Sie für Anfragen den Supportweg in der App."] },
  ] }, terms: { intro: "Diese Bedingungen enthalten die einfachen Regeln für die Nutzung von Notura.", updated: updated.de, sections: [
    { id: "service", heading: "Was Notura ist", paragraphs: ["Notura ist ein Dienst zur Ernährungs- und Wellnessdokumentation. Er hilft beim Erfassen von Mahlzeiten, beim Einordnen von Kalorien und Makronährstoffen sowie beim Verfolgen verwandter Ziele. Notura ist kein Medizinprodukt, kein Diagnosedienst und kein Ersatz für Ärztinnen, Ärzte, Ernährungsfachkräfte oder andere qualifizierte Gesundheitsberufe."] },
    { id: "health-ai", heading: "Gesundheits- und KI-Informationen", paragraphs: ["KI kann bei der Erkennung von Lebensmitteln, Portions- oder Nährwertschätzungen und Vorschlägen Fehler machen. Prüfen Sie Ergebnisse, bevor Sie sich darauf verlassen, und nutzen Sie sie nicht als alleinige Grundlage kritischer Gesundheitsentscheidungen. Bei Allergien, Erkrankungen, Medikamenten, Schwangerschaft oder klinischen Diäten holen Sie fachlichen Rat ein."] },
    { id: "account", heading: "Ihr Konto", paragraphs: ["Sie sind für Aktivitäten über Ihr Konto und die Sicherheit Ihrer Anmeldemethode verantwortlich. Nutzen Sie Notura rechtmäßig und missbrauchen oder stören Sie den Dienst nicht; versuchen Sie nicht, auf fremde Konten oder Daten zuzugreifen. Sie können Ihr Konto löschen. Bei Missbrauch, Sicherheitsrisiko oder rechtlichem Grund können wir den Zugang beschränken oder aussetzen."] },
    { id: "community", heading: "Community-Regeln", paragraphs: ["Falls Community für Sie verfügbar ist, nutzen Sie sie respektvoll und rechtmäßig. Keine Belästigung, kein Spam, keine rechtswidrigen Inhalte, keine Verletzung fremder Rechte und kein Missbrauch. Wir können Community-Inhalte entfernen oder den Zugang beschränken, wenn dies zur Durchsetzung dieser Regeln oder zum Schutz von Menschen und Dienst angemessen nötig ist. Beiträge, Kommentare und Reaktionen werden nach 30 Tagen entfernt; Ihr privater Tagebucheintrag bleibt davon unberührt."] },
    { id: "your-content", heading: "Ihre Inhalte", paragraphs: ["Sie behalten das Eigentum an Ihren Inhalten. Sie erteilen Notura die begrenzte Erlaubnis, sie zu hosten, zu verarbeiten, Ihnen anzuzeigen und – nur bei Ihrer Community-Freigabe – in Community anzuzeigen, soweit dies für den Dienst nötig ist. Diese Erlaubnis endet mit der Löschung des betreffenden Inhalts, vorbehaltlich notwendiger technischer, Sicherheits- und Rechtsaufbewahrung."] },
    { id: "plans", heading: "Kostenlose und kostenpflichtige Funktionen", paragraphs: ["Einige Funktionen können kostenlos sein, andere künftig einen kostenpflichtigen Plan oder Kauf erfordern. Falls eine Zahlung gilt, werden Preis und Zahlungsbedingungen vor dem Kauf angezeigt. Käufe, Wiederherstellungen und Erstattungen über Google Play oder den Apple App Store können zusätzlich den Regeln des jeweiligen Stores unterliegen."] },
    { id: "availability-liability", heading: "Verfügbarkeit und Verantwortung", paragraphs: ["Notura wird nach Verfügbarkeit bereitgestellt. Wir bemühen uns um Nützlichkeit und Zuverlässigkeit, garantieren jedoch weder immer korrekte KI-Ergebnisse noch einen stets unterbrechungsfreien Dienst, auch nicht bei Ausfällen von Drittanbietern. Diese Bedingungen schließen keine Haftung aus, die rechtlich nicht ausgeschlossen werden kann."] },
    { id: "changes-contact", heading: "Änderungen und Kontakt", paragraphs: ["Wir können diese Bedingungen aktualisieren und veröffentlichen die aktuelle Fassung mit Datum auf dieser Seite. Wenn Sie einer wesentlichen Änderung nicht zustimmen, nutzen Sie Notura nicht weiter und löschen Sie Ihr Konto. Eine eigene öffentliche Legal-E-Mail-Adresse ist auf dieser Website noch nicht veröffentlicht; Fragen können über den Supportweg in der App gestellt werden."] },
  ] } },
  es: { privacy: { intro: "Este aviso explica cómo trata Notura la información personal cuando utilizas la aplicación y los servicios relacionados.", updated: updated.es, sections: [
    { id: "information", heading: "Información que recopilamos", paragraphs: ["Recopilamos la información necesaria para tu cuenta y experiencia de seguimiento nutricional: correo electrónico y datos básicos de cuenta, información de perfil que decidas proporcionar, registros de comidas, fotos y descripciones de alimentos, información de calorías y macronutrientes, registros de agua y peso, objetivos y preferencias. Si utilizas Community, también tratamos el contenido, comentarios y reacciones que decidas compartir."] },
    { id: "how-we-use", heading: "Cómo usamos la información", paragraphs: ["Usamos la información para ofrecer y mejorar las funciones que eliges, conservar tus registros en tu cuenta, personalizar ajustes y objetivos, prestar soporte, proteger el servicio y cumplir obligaciones legales. No usamos tu diario personal como contenido público de Community salvo que decidas compartirlo."] },
    { id: "providers-location", heading: "Proveedores y ubicación de los datos", paragraphs: ["Notura utiliza Supabase como proveedor de alojamiento, backend y servicios. Nuestra región principal de servidores y datos es Irlanda, en la Unión Europea. Los proveedores pueden tratar información bajo garantías adecuadas cuando sea necesario para prestar sus servicios; esto no significa que la información nunca pueda consultarse o tratarse fuera de Irlanda."] },
    { id: "sign-in", heading: "Inicio de sesión con Google y Apple", paragraphs: ["El inicio de sesión con Google está disponible mediante un servicio de autenticación de terceros. El inicio de sesión con Apple podría ofrecerse en una versión futura. Si eliges uno de estos métodos, podemos recibir la información básica necesaria para autenticarte y crear tu cuenta de Notura. Notura no recibe tu contraseña de Google ni de Apple."] },
    { id: "ai", heading: "Funciones de IA", paragraphs: ["Notura puede utilizar IA para analizar fotos o descripciones escritas de comidas y para ofrecer sugerencias. Enviamos solo el contenido necesario para la solicitud, como la foto, la descripción o información limitada para una sugerencia. No añadimos tu nombre, correo, identificador de cuenta o historial amplio de perfil a una solicitud de IA cuando no es necesario. Una foto o texto enviado puede contener información personal, por lo que no prometemos de forma absoluta que nunca se envíen datos personales. Los resultados de IA sirven para ayudarte a registrar y revisar comidas."] },
    { id: "community", heading: "Community y la regla de 30 días", paragraphs: ["Compartir en Community está desactivado de forma predeterminada. Tú decides si activarlo y, en el flujo correspondiente, si compartes registros anteriores elegibles. Community conserva y muestra solo publicaciones relevantes de los últimos 30 días. Cuando una publicación cumple 30 días, se elimina de Community junto con sus comentarios y reacciones. Esto no elimina tu registro personal de comida o diario. Puedes ocultar un registro concreto de Community y usar controles disponibles, como bloquear."] },
    { id: "retention-rights", heading: "Conservación, cuenta y tus opciones", paragraphs: ["Conservamos los datos de cuenta y personales mientras sean necesarios para prestar el servicio. Al eliminar tu cuenta, los datos asociados se eliminan sujetos a requisitos técnicos, de seguridad y legales; algunos registros limitados pueden conservarse más tiempo por esos motivos. Community sigue la regla independiente de 30 días. Puedes solicitar acceso, rectificación, eliminación y, cuando esté disponible, exportación de tu información, además de retirar el consentimiento cuando el tratamiento se base en él. Presenta solicitudes de privacidad mediante la opción de soporte de la aplicación."] },
    { id: "regional-rights", heading: "Derechos regionales de privacidad", paragraphs: ["Según dónde vivas, puedes tener derechos adicionales. En Türkiye se reservan los derechos de KVKK. En el EEE y la UE, los derechos del RGPD pueden incluir acceso, rectificación, supresión, limitación, oposición y portabilidad. Pueden aplicarse derechos similares en el Reino Unido bajo UK GDPR y Data Protection Act, en Brasil bajo LGPD y bajo leyes federales o estatales de privacidad aplicables en Estados Unidos. También puedes tener derecho a reclamar ante la autoridad competente."] },
    { id: "security-children", heading: "Seguridad y menores", paragraphs: ["Aplicamos medidas técnicas y organizativas razonables para proteger la información. Ningún servicio de internet es completamente seguro. Notura no ha establecido una edad mínima pública en este sitio web. Si sabemos que se recopiló información de un menor contraviniendo la ley aplicable, tomaremos medidas adecuadas."] },
    { id: "changes-contact", heading: "Cambios y contacto", paragraphs: ["Podemos actualizar este aviso si cambia Notura o la legislación aplicable. Publicaremos aquí la versión actual y su fecha. Este sitio web aún no publica una dirección de correo específica de privacidad; utiliza la vía de soporte disponible en la aplicación para las solicitudes."] },
  ] }, terms: { intro: "Estos términos establecen las reglas sencillas para usar Notura.", updated: updated.es, sections: [
    { id: "service", heading: "Qué es Notura", paragraphs: ["Notura es un servicio de seguimiento de nutrición y bienestar. Puede ayudarte a registrar alimentos, entender el contexto de calorías y macronutrientes y seguir objetivos relacionados. No es un dispositivo médico, servicio de diagnóstico ni sustituto de un médico, dietista u otro profesional sanitario cualificado."] },
    { id: "health-ai", heading: "Información de salud e IA", paragraphs: ["La IA puede equivocarse al identificar alimentos, estimar porciones o valores nutricionales y hacer sugerencias. Revisa los resultados antes de confiar en ellos y no los uses como única base para decisiones de salud importantes. Para alergias, enfermedades, medicamentos, embarazo o una dieta clínica, consulta a un profesional sanitario cualificado."] },
    { id: "account", heading: "Tu cuenta", paragraphs: ["Eres responsable de la actividad de tu cuenta y de mantener seguro tu método de inicio de sesión. Usa Notura legalmente y no abuses, interfieras ni intentes acceder a cuentas o datos ajenos. Puedes eliminar tu cuenta. Podemos limitar o suspender el acceso si hay uso indebido, riesgo de seguridad o motivo legal."] },
    { id: "community", heading: "Reglas de Community", paragraphs: ["Si Community está disponible para ti, úsala con respeto y de forma legal. No publiques acoso, spam, contenido ilegal, contenido que infrinja derechos ajenos ni contenido que haga un mal uso del servicio. Podemos retirar contenido de Community o limitar el acceso cuando sea razonablemente necesario para aplicar estas reglas o proteger a las personas y el servicio. Las publicaciones, comentarios y reacciones se eliminan después de 30 días; este proceso no elimina tu registro privado."] },
    { id: "your-content", heading: "Tu contenido", paragraphs: ["Conservas la titularidad de lo que envías. Concedes a Notura el permiso limitado necesario para alojarlo, tratarlo, mostrártelo y, solo si eliges compartirlo en Community, mostrarlo allí, para prestar el servicio. Ese permiso termina al eliminarse el contenido correspondiente, salvo la conservación técnica, de seguridad o legal necesaria."] },
    { id: "plans", heading: "Funciones gratuitas y de pago", paragraphs: ["Algunas funciones pueden ser gratuitas y otras podrían requerir un plan de pago o compra en el futuro. Si se aplica un pago, el precio y las condiciones aparecerán antes de la compra. Las compras, restauraciones y reembolsos mediante Google Play o Apple App Store también pueden regirse por las reglas de esa tienda."] },
    { id: "availability-liability", heading: "Disponibilidad y responsabilidad", paragraphs: ["Notura se ofrece según disponibilidad. Trabajamos para que sea útil y fiable, pero no garantizamos que los resultados de IA sean siempre correctos ni que el servicio esté siempre ininterrumpido, incluso si fallan servicios de terceros. Nada de estos términos excluye una responsabilidad que no pueda excluirse legalmente."] },
    { id: "changes-contact", heading: "Cambios y contacto", paragraphs: ["Podemos actualizar estos términos y publicaremos la versión vigente con su fecha en esta página. Si no aceptas un cambio importante, deja de usar Notura y elimina tu cuenta. Este sitio web aún no publica un correo legal específico; usa la vía de soporte disponible en la aplicación para consultas."] },
  ] } },
  fr: { privacy: { intro: "Cet avis explique comment Notura traite les informations personnelles lorsque vous utilisez l’application et les services associés.", updated: updated.fr, sections: [
    { id: "information", heading: "Informations que nous collectons", paragraphs: ["Nous collectons les informations nécessaires à votre compte et au suivi nutritionnel : adresse e-mail et données de compte de base, informations de profil que vous choisissez de fournir, entrées de repas, photos et descriptions de repas, calories et macronutriments, données d’eau et de poids, objectifs et préférences. Si vous utilisez Community, nous traitons aussi le contenu, les commentaires et les réactions que vous choisissez de partager."] },
    { id: "how-we-use", heading: "Utilisation des informations", paragraphs: ["Nous utilisons ces informations pour fournir et améliorer les fonctions choisies, garder vos données disponibles dans votre compte, adapter vos réglages et objectifs, fournir de l’assistance, protéger le service et respecter nos obligations légales. Nous n’utilisons pas votre journal personnel comme contenu Community public sauf si vous choisissez de le partager."] },
    { id: "providers-location", heading: "Prestataires et localisation des données", paragraphs: ["Notura utilise Supabase comme prestataire d’hébergement, de backend et de services. Notre région principale de serveurs et de données est l’Irlande, dans l’Union européenne. Les prestataires peuvent traiter des informations sous garanties appropriées lorsque cela est nécessaire à leurs services ; cela ne signifie pas que les informations ne pourront jamais être consultées ou traitées hors d’Irlande."] },
    { id: "sign-in", heading: "Connexion avec Google et Apple", paragraphs: ["La connexion Google est disponible via un service d’authentification tiers. La connexion Apple pourra être proposée dans une version future. Si vous choisissez l’une de ces méthodes, nous pouvons recevoir les informations de compte de base nécessaires à votre authentification et à la création de votre compte Notura. Notura ne reçoit pas votre mot de passe Google ou Apple."] },
    { id: "ai", heading: "Fonctions d’IA", paragraphs: ["Notura peut utiliser l’IA pour analyser une photo ou une description écrite de repas et proposer des suggestions. Nous n’envoyons que le contenu nécessaire à la demande : photo, description ou informations limitées nécessaires à une suggestion. Nous n’ajoutons pas votre nom, e-mail, identifiant de compte ou historique de profil étendu à une demande d’IA lorsqu’ils ne sont pas nécessaires. Une photo ou un texte soumis peut contenir des informations personnelles ; nous ne promettons donc pas de façon absolue qu’aucune donnée personnelle n’est jamais envoyée. Les résultats d’IA servent à vous aider à enregistrer et vérifier vos repas."] },
    { id: "community", heading: "Community et la règle des 30 jours", paragraphs: ["Le partage Community est désactivé par défaut. Vous décidez de l’activer et, dans le parcours concerné, de partager ou non des enregistrements passés admissibles. Community ne conserve et n’affiche que les partages pertinents des 30 derniers jours. Lorsqu’une publication atteint 30 jours, elle est retirée de Community avec ses commentaires et réactions. Cela ne supprime pas votre entrée personnelle de repas ou de journal. Vous pouvez masquer une entrée particulière de Community et utiliser les contrôles disponibles, comme le blocage."] },
    { id: "retention-rights", heading: "Conservation, compte et vos choix", paragraphs: ["Nous conservons les données de compte et personnelles aussi longtemps que nécessaire au service. Lorsque vous supprimez votre compte, les données associées sont supprimées sous réserve des exigences techniques, de sécurité et légales ; certains enregistrements limités peuvent être conservés plus longtemps pour ces raisons. Community suit sa règle distincte de 30 jours. Vous pouvez demander l’accès, la rectification, la suppression et, lorsqu’elle existe, l’exportation de vos informations, ainsi que retirer votre consentement lorsque le traitement repose sur lui. Adressez vos demandes de confidentialité via l’option d’assistance de l’application."] },
    { id: "regional-rights", heading: "Droits régionaux en matière de confidentialité", paragraphs: ["Selon votre lieu de résidence, vous pouvez bénéficier de droits supplémentaires. En Türkiye, les droits prévus par la KVKK sont réservés. Dans l’EEE et l’UE, les droits RGPD peuvent comprendre l’accès, la rectification, l’effacement, la limitation, l’opposition et la portabilité. Des droits comparables peuvent s’appliquer au Royaume-Uni sous UK GDPR et Data Protection Act, au Brésil sous LGPD et en vertu des lois fédérales ou étatiques applicables aux États-Unis. Vous pouvez aussi avoir le droit de vous plaindre auprès de l’autorité compétente."] },
    { id: "security-children", heading: "Sécurité et enfants", paragraphs: ["Nous appliquons des mesures techniques et organisationnelles raisonnables pour protéger les informations. Aucun service internet n’est totalement sécurisé. Notura n’a pas fixé de seuil d’âge public sur ce site. Si nous apprenons que des informations d’un enfant ont été collectées contrairement au droit applicable, nous prendrons les mesures appropriées."] },
    { id: "changes-contact", heading: "Modifications et contact", paragraphs: ["Nous pouvons mettre à jour cet avis à mesure que Notura ou le droit applicable évolue. La version en vigueur et sa date de mise à jour seront publiées ici. Une adresse e-mail publique dédiée à la confidentialité n’est pas encore publiée sur ce site ; utilisez le canal d’assistance disponible dans l’application pour vos demandes."] },
  ] }, terms: { intro: "Ces conditions présentent les règles simples d’utilisation de Notura.", updated: updated.fr, sections: [
    { id: "service", heading: "Ce qu’est Notura", paragraphs: ["Notura est un service de suivi de la nutrition et du bien-être. Il peut vous aider à enregistrer les repas, comprendre le contexte des calories et macronutriments et suivre des objectifs associés. Ce n’est ni un dispositif médical, ni un service de diagnostic, ni un substitut à un médecin, un diététicien ou un autre professionnel de santé qualifié."] },
    { id: "health-ai", heading: "Santé et informations d’IA", paragraphs: ["L’IA peut se tromper en identifiant les aliments, en estimant les portions ou les valeurs nutritionnelles et en faisant des suggestions. Vérifiez les résultats avant de vous y fier et ne les utilisez pas comme seule base de décisions de santé importantes. En cas d’allergie, maladie, médicament, grossesse ou régime clinique, demandez conseil à un professionnel de santé qualifié."] },
    { id: "account", heading: "Votre compte", paragraphs: ["Vous êtes responsable de l’activité de votre compte et de la sécurité de votre méthode de connexion. Utilisez Notura légalement, sans en faire un usage abusif, sans perturber le service et sans tenter d’accéder à des comptes ou données qui ne vous appartiennent pas. Vous pouvez supprimer votre compte. Nous pouvons limiter ou suspendre l’accès en cas d’usage abusif, de risque de sécurité ou de motif légal."] },
    { id: "community", heading: "Règles Community", paragraphs: ["Si Community vous est disponible, utilisez-la avec respect et conformément à la loi. Ne publiez pas de harcèlement, spam, contenu illégal, contenu portant atteinte aux droits d’autrui ou contenu détournant le service. Nous pouvons retirer du contenu Community ou limiter l’accès lorsque cela est raisonnablement nécessaire pour appliquer ces règles ou protéger les personnes et le service. Publications, commentaires et réactions sont supprimés après 30 jours ; ce processus ne supprime pas votre journal privé."] },
    { id: "your-content", heading: "Votre contenu", paragraphs: ["Vous conservez la propriété du contenu envoyé. Vous accordez à Notura l’autorisation limitée nécessaire pour l’héberger, le traiter, vous l’afficher et, uniquement si vous choisissez le partage Community, l’afficher dans Community afin de fournir le service. Cette autorisation prend fin lorsque le contenu concerné est supprimé, sous réserve de la conservation technique, de sécurité ou légale nécessaire."] },
    { id: "plans", heading: "Fonctions gratuites et payantes", paragraphs: ["Certaines fonctions peuvent être gratuites et d’autres pourront nécessiter une formule ou un achat payant à l’avenir. Si un paiement s’applique, le prix et les conditions seront indiqués avant l’achat. Les achats, restaurations et remboursements effectués via Google Play ou l’App Store d’Apple peuvent aussi être régis par les règles de cette boutique."] },
    { id: "availability-liability", heading: "Disponibilité et responsabilité", paragraphs: ["Notura est fourni selon sa disponibilité. Nous nous efforçons de le rendre utile et fiable, sans garantir que les résultats d’IA soient toujours exacts ni que le service soit toujours ininterrompu, y compris lors d’une indisponibilité de services tiers. Rien dans ces conditions n’exclut une responsabilité qui ne peut être légalement exclue."] },
    { id: "changes-contact", heading: "Modifications et contact", paragraphs: ["Nous pouvons mettre à jour ces conditions et publierons la version en vigueur avec sa date sur cette page. Si vous n’acceptez pas une modification importante, cessez d’utiliser Notura et supprimez votre compte. Une adresse e-mail juridique publique dédiée n’est pas encore publiée sur ce site ; utilisez le canal d’assistance disponible dans l’application pour vos questions."] },
  ] } },
  it: { privacy: { intro: "Questa informativa spiega come Notura tratta le informazioni personali quando usi l’app e i servizi correlati.", updated: updated.it, sections: [
    { id: "information", heading: "Informazioni che raccogliamo", paragraphs: ["Raccogliamo le informazioni necessarie per il tuo account e per il monitoraggio nutrizionale: email e dati essenziali dell’account, informazioni del profilo che scegli di fornire, registrazioni dei pasti, foto e descrizioni degli alimenti, calorie e macronutrienti, dati su acqua e peso, obiettivi e preferenze. Se usi Community, trattiamo anche contenuti, commenti e reazioni che scegli di condividere."] },
    { id: "how-we-use", heading: "Come usiamo le informazioni", paragraphs: ["Usiamo queste informazioni per fornire e migliorare le funzioni che scegli, mantenere i tuoi dati disponibili nell’account, personalizzare impostazioni e obiettivi, offrire assistenza, proteggere il servizio e rispettare obblighi legali. Non usiamo il tuo diario personale come contenuto pubblico di Community salvo tua scelta."] },
    { id: "providers-location", heading: "Fornitori e posizione dei dati", paragraphs: ["Notura usa Supabase come fornitore di hosting, backend e servizi. La nostra principale regione di server e dati è l’Irlanda, nell’Unione europea. I fornitori possono trattare informazioni con adeguate garanzie quando necessario ai loro servizi; questo non significa che le informazioni non possano mai essere consultate o trattate fuori dall’Irlanda."] },
    { id: "sign-in", heading: "Accesso con Google e Apple", paragraphs: ["L’accesso con Google è disponibile tramite un servizio di autenticazione di terze parti. L’accesso con Apple potrebbe essere offerto in una versione futura. Se scegli uno di questi metodi, possiamo ricevere le informazioni essenziali necessarie per autenticarti e creare l’account Notura. Notura non riceve la tua password Google o Apple."] },
    { id: "ai", heading: "Funzioni di IA", paragraphs: ["Notura può usare l’IA per analizzare foto o descrizioni scritte dei pasti e per proporre suggerimenti. Inviamo solo il contenuto necessario alla richiesta, come foto, descrizione o informazioni limitate per un suggerimento. Non aggiungiamo nome, email, identificativo dell’account o ampia cronologia del profilo a una richiesta di IA quando non necessari. Una foto o un testo inviato può contenere dati personali; non promettiamo quindi in modo assoluto che nessun dato personale venga mai inviato. I risultati dell’IA servono ad aiutarti a registrare e rivedere i pasti."] },
    { id: "community", heading: "Community e la regola dei 30 giorni", paragraphs: ["La condivisione in Community è disattivata per impostazione predefinita. Decidi tu se abilitarla e, nel flusso pertinente, se condividere registri passati idonei. Community conserva e mostra solo condivisioni pertinenti degli ultimi 30 giorni. Quando un post raggiunge 30 giorni viene rimosso da Community insieme a commenti e reazioni. Questo non elimina la registrazione personale del pasto o del diario. Puoi nascondere un singolo record da Community e usare i controlli disponibili, come il blocco."] },
    { id: "retention-rights", heading: "Conservazione, account e tue scelte", paragraphs: ["Conserviamo dati dell’account e personali finché necessari a fornire il servizio. Quando elimini l’account, i dati associati vengono eliminati nel rispetto di requisiti tecnici, di sicurezza e legali; alcuni registri limitati possono essere conservati più a lungo per tali motivi. Community segue la distinta regola di 30 giorni. Puoi chiedere accesso, rettifica, cancellazione e, quando disponibile, esportazione delle tue informazioni, e ritirare il consenso quando il trattamento si basa su di esso. Invia le richieste privacy tramite l’opzione di assistenza nell’app."] },
    { id: "regional-rights", heading: "Diritti privacy regionali", paragraphs: ["In base al luogo in cui vivi, potresti avere diritti aggiuntivi. In Türkiye sono riservati i diritti previsti dalla KVKK. Nello SEE e nell’UE i diritti GDPR possono comprendere accesso, rettifica, cancellazione, limitazione, opposizione e portabilità. Diritti analoghi possono applicarsi nel Regno Unito ai sensi di UK GDPR e Data Protection Act, in Brasile ai sensi di LGPD e negli Stati Uniti secondo le leggi federali o statali applicabili. Potresti anche avere il diritto di presentare reclamo all’autorità competente."] },
    { id: "security-children", heading: "Sicurezza e minori", paragraphs: ["Adottiamo misure tecniche e organizzative ragionevoli per proteggere le informazioni. Nessun servizio internet è completamente sicuro. Notura non ha definito una soglia d’età pubblica su questo sito. Se veniamo a sapere che sono state raccolte informazioni di un minore in violazione della legge applicabile, adotteremo misure appropriate."] },
    { id: "changes-contact", heading: "Modifiche e contatti", paragraphs: ["Possiamo aggiornare questa informativa quando cambiano Notura o la normativa applicabile. Qui pubblicheremo la versione corrente e la data di aggiornamento. Questo sito non pubblica ancora un indirizzo email privacy dedicato; per le richieste usa il canale di assistenza disponibile nell’app."] },
  ] }, terms: { intro: "Questi termini stabiliscono le semplici regole per l’uso di Notura.", updated: updated.it, sections: [
    { id: "service", heading: "Cos’è Notura", paragraphs: ["Notura è un servizio di monitoraggio della nutrizione e del benessere. Può aiutarti a registrare cibi, comprendere il contesto di calorie e macronutrienti e seguire obiettivi correlati. Non è un dispositivo medico, un servizio diagnostico né un sostituto di medico, dietista o altro professionista sanitario qualificato."] },
    { id: "health-ai", heading: "Informazioni su salute e IA", paragraphs: ["L’IA può sbagliare nell’identificare alimenti, stimare porzioni o valori nutrizionali e formulare suggerimenti. Controlla i risultati prima di farvi affidamento e non usarli come unica base per decisioni sanitarie importanti. Per allergie, malattie, farmaci, gravidanza o dieta clinica, chiedi consiglio a un professionista sanitario qualificato."] },
    { id: "account", heading: "Il tuo account", paragraphs: ["Sei responsabile dell’attività svolta tramite il tuo account e della sicurezza del metodo di accesso. Usa Notura legalmente e non abusarne, non interferire con il servizio e non tentare di accedere a account o dati altrui. Puoi eliminare il tuo account. Possiamo limitare o sospendere l’accesso in caso di abuso, rischio per la sicurezza o motivo legale."] },
    { id: "community", heading: "Regole di Community", paragraphs: ["Se Community è disponibile per te, usala con rispetto e nel rispetto della legge. Non pubblicare molestie, spam, contenuti illegali, contenuti che violano diritti altrui o contenuti che abusano del servizio. Possiamo rimuovere contenuti Community o limitare l’accesso quando ragionevolmente necessario per applicare queste regole o proteggere persone e servizio. Post, commenti e reazioni vengono rimossi dopo 30 giorni; il tuo diario privato non viene rimosso da questo processo."] },
    { id: "your-content", heading: "I tuoi contenuti", paragraphs: ["Mantieni la proprietà dei contenuti inviati. Concedi a Notura il permesso limitato necessario per ospitarli, trattarli, mostrarteli e, solo se scegli la condivisione in Community, mostrarli in Community, così da fornire il servizio. Il permesso termina quando il contenuto pertinente viene eliminato, salvo la necessaria conservazione tecnica, di sicurezza o legale."] },
    { id: "plans", heading: "Funzioni gratuite e a pagamento", paragraphs: ["Alcune funzioni possono essere gratuite e altre potrebbero richiedere in futuro un piano o acquisto a pagamento. Se si applica un pagamento, prezzo e condizioni saranno mostrati prima dell’acquisto. Acquisti, ripristini e rimborsi tramite Google Play o Apple App Store possono essere disciplinati anche dalle regole dello store."] },
    { id: "availability-liability", heading: "Disponibilità e responsabilità", paragraphs: ["Notura è fornita secondo disponibilità. Lavoriamo per renderla utile e affidabile, ma non garantiamo che i risultati di IA siano sempre corretti né che il servizio sia sempre ininterrotto, anche in caso di indisponibilità di servizi di terze parti. Nulla in questi termini esclude responsabilità che non possa essere legalmente esclusa."] },
    { id: "changes-contact", heading: "Modifiche e contatti", paragraphs: ["Possiamo aggiornare questi termini e pubblicheremo la versione corrente con la data su questa pagina. Se non accetti una modifica sostanziale, smetti di usare Notura ed elimina il tuo account. Questo sito non pubblica ancora un indirizzo email legale dedicato; usa il canale di assistenza disponibile nell’app per le domande."] },
  ] } },
  "pt-br": { privacy: { intro: "Este aviso explica como a Notura trata informações pessoais quando você usa o aplicativo e serviços relacionados.", updated: updated["pt-br"], sections: [
    { id: "information", heading: "Informações que coletamos", paragraphs: ["Coletamos as informações necessárias para sua conta e sua experiência de acompanhamento nutricional: e-mail e dados básicos da conta, informações de perfil que você escolher fornecer, registros de refeições, fotos e descrições de alimentos, calorias e macronutrientes, registros de água e peso, objetivos e preferências. Se usar o Community, também tratamos o conteúdo, comentários e reações que você escolher compartilhar."] },
    { id: "how-we-use", heading: "Como usamos as informações", paragraphs: ["Usamos essas informações para fornecer e melhorar os recursos escolhidos, manter seus registros disponíveis na conta, personalizar configurações e metas, prestar suporte, proteger o serviço e cumprir obrigações legais. Não usamos seu diário pessoal como conteúdo público do Community, a menos que você escolha compartilhá-lo."] },
    { id: "providers-location", heading: "Prestadores e localização dos dados", paragraphs: ["A Notura usa o Supabase como provedor de hospedagem, backend e serviços. Nossa região principal de servidores e dados é a Irlanda, na União Europeia. Prestadores podem tratar informações com salvaguardas adequadas quando isso for necessário aos seus serviços; isso não significa que as informações nunca possam ser acessadas ou tratadas fora da Irlanda."] },
    { id: "sign-in", heading: "Login com Google e Apple", paragraphs: ["O login com Google está disponível por meio de um serviço de autenticação de terceiros. O login com Apple poderá ser oferecido em uma versão futura. Ao escolher um desses métodos, podemos receber as informações básicas necessárias para autenticar você e criar sua conta Notura. A Notura não recebe sua senha do Google ou da Apple."] },
    { id: "ai", heading: "Recursos de IA", paragraphs: ["A Notura pode usar IA para analisar fotos ou descrições escritas de refeições e oferecer sugestões. Enviamos apenas o conteúdo necessário para a solicitação, como a foto, sua descrição ou informações limitadas para uma sugestão. Não acrescentamos seu nome, e-mail, identificador da conta ou histórico amplo do perfil a uma solicitação de IA quando não são necessários. Uma foto ou texto enviado pode conter informação pessoal; por isso, não prometemos de forma absoluta que nenhum dado pessoal será enviado. Os resultados de IA servem para ajudar você a registrar e revisar refeições."] },
    { id: "community", heading: "Community e a regra de 30 dias", paragraphs: ["O compartilhamento no Community fica desativado por padrão. Você escolhe se quer ativá-lo e, no fluxo apropriado, se deseja compartilhar registros anteriores elegíveis. O Community mantém e mostra somente compartilhamentos relevantes dos últimos 30 dias. Quando uma publicação completa 30 dias, ela é removida do Community junto com seus comentários e reações. Isso não exclui seu registro pessoal de refeição ou diário. Você pode ocultar um registro específico do Community e usar controles disponíveis, como bloqueio."] },
    { id: "retention-rights", heading: "Retenção, conta e suas escolhas", paragraphs: ["Mantemos os dados da conta e do aplicativo enquanto forem necessários para prestar o serviço. Quando você exclui a conta, os dados associados são excluídos sujeitos a requisitos técnicos, de segurança e legais; alguns registros limitados podem ser retidos por mais tempo por esses motivos. O Community segue a regra separada de 30 dias. Você pode solicitar acesso, correção, exclusão e, quando disponível, exportação de suas informações, além de retirar o consentimento quando o tratamento depender dele. Faça pedidos de privacidade pela opção de suporte disponível no aplicativo."] },
    { id: "regional-rights", heading: "Direitos regionais de privacidade", paragraphs: ["Dependendo de onde você mora, pode ter direitos adicionais. Na Türkiye, ficam resguardados os direitos previstos na KVKK. No EEE e na UE, direitos do GDPR podem incluir acesso, correção, exclusão, restrição, oposição e portabilidade. Direitos semelhantes podem se aplicar no Reino Unido sob UK GDPR e Data Protection Act, no Brasil sob LGPD e sob leis federais ou estaduais de privacidade aplicáveis nos Estados Unidos. Você também pode ter o direito de reclamar à autoridade de proteção de dados competente."] },
    { id: "security-children", heading: "Segurança e crianças", paragraphs: ["Usamos medidas técnicas e organizacionais razoáveis para proteger informações. Nenhum serviço de internet é completamente seguro. A Notura não definiu uma idade mínima pública neste site. Se soubermos que informações de uma criança foram coletadas em desacordo com a lei aplicável, tomaremos medidas apropriadas."] },
    { id: "changes-contact", heading: "Alterações e contato", paragraphs: ["Podemos atualizar este aviso conforme a Notura ou a legislação aplicável mudem. A versão vigente e a data de atualização serão publicadas aqui. Este site ainda não publica um e-mail público específico de privacidade; use o canal de suporte disponível no aplicativo para solicitações."] },
  ] }, terms: { intro: "Estes termos estabelecem as regras simples para usar a Notura.", updated: updated["pt-br"], sections: [
    { id: "service", heading: "O que é a Notura", paragraphs: ["A Notura é um serviço de acompanhamento de nutrição e bem-estar. Ela pode ajudar você a registrar alimentos, entender o contexto de calorias e macronutrientes e acompanhar metas relacionadas. Não é um dispositivo médico, serviço de diagnóstico ou substituto de médico, nutricionista ou outro profissional de saúde qualificado."] },
    { id: "health-ai", heading: "Informações de saúde e IA", paragraphs: ["A IA pode errar ao identificar alimentos, estimar porções ou valores nutricionais e fazer sugestões. Revise os resultados antes de confiar neles e não os use como única base para decisões importantes de saúde. Para alergias, doenças, medicamentos, gravidez ou dieta clínica, procure orientação de um profissional de saúde qualificado."] },
    { id: "account", heading: "Sua conta", paragraphs: ["Você é responsável pela atividade em sua conta e por manter seu método de login seguro. Use a Notura de forma legal e não abuse, interfira ou tente acessar contas ou dados de outras pessoas. Você pode excluir sua conta. Podemos limitar ou suspender o acesso em caso de uso indevido, risco de segurança ou motivo legal."] },
    { id: "community", heading: "Regras do Community", paragraphs: ["Se o Community estiver disponível para você, use-o com respeito e dentro da lei. Não publique assédio, spam, conteúdo ilegal, conteúdo que infrinja direitos de terceiros ou conteúdo que use indevidamente o serviço. Podemos remover conteúdo do Community ou limitar o acesso quando razoavelmente necessário para aplicar estas regras ou proteger pessoas e o serviço. Publicações, comentários e reações são removidos após 30 dias; esse processo não exclui seu diário privado."] },
    { id: "your-content", heading: "Seu conteúdo", paragraphs: ["Você mantém a propriedade do conteúdo que envia. Você concede à Notura a permissão limitada necessária para hospedá-lo, processá-lo, mostrá-lo a você e, apenas se escolher compartilhar no Community, mostrá-lo lá, para que possamos prestar o serviço. Essa permissão termina quando o conteúdo relevante é excluído, sujeita à retenção técnica, de segurança e legal necessária."] },
    { id: "plans", heading: "Recursos gratuitos e pagos", paragraphs: ["Alguns recursos podem ser gratuitos e outros podem exigir plano pago ou compra no futuro. Se houver pagamento, o preço e as condições serão mostrados antes da compra. Compras, restaurações e reembolsos por Google Play ou Apple App Store também podem ser regidos pelas regras da loja."] },
    { id: "availability-liability", heading: "Disponibilidade e responsabilidade", paragraphs: ["A Notura é fornecida conforme disponibilidade. Trabalhamos para mantê-la útil e confiável, mas não garantimos que resultados de IA sejam sempre corretos ou que o serviço esteja sempre ininterrupto, inclusive quando serviços de terceiros estiverem indisponíveis. Nada nestes termos exclui responsabilidade que não possa ser excluída por lei."] },
    { id: "changes-contact", heading: "Alterações e contato", paragraphs: ["Podemos atualizar estes termos e publicaremos a versão vigente com a data nesta página. Se você não aceitar uma alteração relevante, deixe de usar a Notura e exclua sua conta. Este site ainda não publica um e-mail jurídico público específico; use o canal de suporte disponível no aplicativo para dúvidas."] },
  ] } },
};

export function getLegalDocument(localeId: string, page: LegalPage): LegalDocument {
  const locale = localeId in documents ? (localeId as keyof typeof documents) : "en";
  return documents[locale][page];
}

export function getLegalContentsLabel(localeId: string): string {
  const locale = localeId in contentsLabels ? (localeId as keyof typeof contentsLabels) : "en";
  return contentsLabels[locale];
}
